-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 06:48:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema planit_food_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema planit_food_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planit_food_db` DEFAULT CHARACTER SET utf8 ;
USE `planit_food_db` ;

-- -----------------------------------------------------
-- Table `planit_food_db`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planit_food_db`.`Tags` ;

CREATE TABLE IF NOT EXISTS `planit_food_db`.`Tags` (
  `idTags` INT NOT NULL AUTO_INCREMENT,
  `tagName` VARCHAR(50) NOT NULL,
  `tagColour` VARCHAR(45) NULL,
  PRIMARY KEY (`idTags`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `tagName_UNIQUE` ON `planit_food_db`.`Tags` (`tagName` ASC);

CREATE UNIQUE INDEX `idTags_UNIQUE` ON `planit_food_db`.`Tags` (`idTags` ASC);


-- -----------------------------------------------------
-- Table `planit_food_db`.`CookBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planit_food_db`.`CookBooks` ;

CREATE TABLE IF NOT EXISTS `planit_food_db`.`CookBooks` (
  `idCookBooks` INT NOT NULL AUTO_INCREMENT,
  `bookName` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCookBooks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planit_food_db`.`Recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planit_food_db`.`Recipes` ;

CREATE TABLE IF NOT EXISTS `planit_food_db`.`Recipes` (
  `idRecipes` INT NOT NULL AUTO_INCREMENT,
  `recipeName` VARCHAR(45) NOT NULL,
  `CookBooks_idCookBooks` INT NULL,
  `pageNumber` INT UNSIGNED NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecipes`),
  CONSTRAINT `fk_Recipes_CookBooks1`
    FOREIGN KEY (`CookBooks_idCookBooks`)
    REFERENCES `planit_food_db`.`CookBooks` (`idCookBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Recipes_CookBooks1_idx` ON `planit_food_db`.`Recipes` (`CookBooks_idCookBooks` ASC);

CREATE INDEX `recipeName` ON `planit_food_db`.`Recipes` (`recipeName` ASC);


-- -----------------------------------------------------
-- Table `planit_food_db`.`DayCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planit_food_db`.`DayCard` ;

CREATE TABLE IF NOT EXISTS `planit_food_db`.`DayCard` (
  `idDayCard` INT NOT NULL,
  `date` DATE NOT NULL,
  `mealTimeCode` CHAR(1) NULL,
  PRIMARY KEY (`idDayCard`, `date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planit_food_db`.`Tags_has_Recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planit_food_db`.`Tags_has_Recipes` ;

CREATE TABLE IF NOT EXISTS `planit_food_db`.`Tags_has_Recipes` (
  `Tags_idTags` INT NOT NULL,
  `Recipes_idRecipes` INT NOT NULL,
  PRIMARY KEY (`Tags_idTags`, `Recipes_idRecipes`),
  CONSTRAINT `fk_Tags_has_Recipes_Tags1`
    FOREIGN KEY (`Tags_idTags`)
    REFERENCES `planit_food_db`.`Tags` (`idTags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_has_Recipes_Recipes1`
    FOREIGN KEY (`Recipes_idRecipes`)
    REFERENCES `planit_food_db`.`Recipes` (`idRecipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tags_has_Recipes_Recipes1_idx` ON `planit_food_db`.`Tags_has_Recipes` (`Recipes_idRecipes` ASC);

CREATE INDEX `fk_Tags_has_Recipes_Tags1_idx` ON `planit_food_db`.`Tags_has_Recipes` (`Tags_idTags` ASC);


-- -----------------------------------------------------
-- Table `planit_food_db`.`DayCard_has_Recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planit_food_db`.`DayCard_has_Recipes` ;

CREATE TABLE IF NOT EXISTS `planit_food_db`.`DayCard_has_Recipes` (
  `DayCard_idDayCard` INT NOT NULL,
  `Recipes_idRecipes` INT NOT NULL,
  PRIMARY KEY (`DayCard_idDayCard`, `Recipes_idRecipes`),
  CONSTRAINT `fk_DayCard_has_Recipes_DayCard1`
    FOREIGN KEY (`DayCard_idDayCard`)
    REFERENCES `planit_food_db`.`DayCard` (`idDayCard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DayCard_has_Recipes_Recipes1`
    FOREIGN KEY (`Recipes_idRecipes`)
    REFERENCES `planit_food_db`.`Recipes` (`idRecipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DayCard_has_Recipes_Recipes1_idx` ON `planit_food_db`.`DayCard_has_Recipes` (`Recipes_idRecipes` ASC);

CREATE INDEX `fk_DayCard_has_Recipes_DayCard1_idx` ON `planit_food_db`.`DayCard_has_Recipes` (`DayCard_idDayCard` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
